Add namespace field in each istio component health
kiali/kiali-operator pull request #128
Opened 2020-09-15 15:20 UTC by xeviknal

Related to https://github.com/kiali/kiali/pull/3211

It allows users to specify the namespace of each istio component. It defaults to the `istio_namespace`. This way the user doesn't have to specify each namespace for each component.

2020-09-15 15:25 UTC, jmazzitelli requested changes

2020-09-15 15:25 UTC, jmazzitelli commented on deploy/kiali/kiali_cr.yaml
> +#       namespace: The namespace where Jaeger is installed in. It defaults to the 'istio_namespace' setting.
You should at least set these four settings to `""` in the defaults/main.yml so the Kiali CR still sets it. The server can default to what it wants if its "" but we should have all defaults explicitly defined (only in rare cases do we leave values completely undefined).

2020-09-15 16:38 UTC, jmazzitelli submitted a review, later dismissed
lgtm

2020-09-16 08:42 UTC, lucasponce approved these changes

2020-09-16 08:42 UTC, lucasponce requested changes
Rebase needed

2020-09-16 08:49 UTC, xeviknal commented
@lucasponce rebase done

2020-09-16 08:52 UTC, lucasponce approved these changes

2020-09-16 08:52 UTC, merged