[1.24] Remove ServiceMeshPolicy and SMRbacConfig for Maistra installations
kiali/kiali-operator pull request #152
Opened 2020-09-29 15:56 UTC by xeviknal

cherry-pick of https://github.com/kiali/kiali-operator/pull/144

2020-09-29 16:42 UTC, jmazzitelli requested changes
Same as the other PR - remove these from the v1.24 roles as well.

2020-09-30 06:44 UTC, xeviknal commented
@jmazzitelli cherry-pick from other PR done.

2020-09-30 12:14 UTC, jmazzitelli approved these changes
LGTM

2020-09-30 14:44 UTC, lucasponce approved these changes

2020-09-30 14:44 UTC, merged

2020-10-12 14:08 UTC, jmazzitelli commented on manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
> -          - watch
we need to revert this change to the ossm golden copy - in order to support installing the older 1.12 stuff, these permissions are still required.

2020-10-12 14:27 UTC, jmazzitelli commented on manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
> -          - watch
revert PRs:
* https://github.com/kiali/kiali-operator/pull/159
* https://github.com/kiali/kiali-operator/pull/160