Remove ComponentStatus from external_services (jaeger, grafana, prom)
kiali/kiali-operator pull request #195
Opened 2020-11-11 14:22 UTC by xeviknal

Requires https://github.com/kiali/kiali/pull/3423

It remove the ComponentStatus from jaeger, prom and grafana. It leaves only one param for users tune the severity of the status in the masthead.

2020-11-11 18:20 UTC, hhovsepy approved these changes

2020-11-11 19:02 UTC, jmazzitelli requested changes
Looks like this is removing some settings that the `null-cr-values-test` molecule test is setting.

See: https://github.com/kiali/kiali-operator/blob/master/molecule/null-cr-values-test/kiali-cr.yaml#L72 (and other places). Just make sure that test CR is still valid.

2020-11-11 19:05 UTC, jmazzitelli commented on roles/default/kiali-deploy/defaults/main.yml
> -        namespace: ""
Does Prometheus have a "core_component" field also? If so, it should be specified here and documented in the `kiali_cr.yaml` so users know about it.

2020-11-12 11:29 UTC, xeviknal commented
I've updated the molecule test for the nulls replacing the previous flag by the new one.
thank you @hhovsepy and @jmazzitelli.

2020-11-12 13:07 UTC, jmazzitelli submitted a review, later dismissed
LGTM

2020-11-13 07:51 UTC, jotak commented on deploy/kiali/kiali_cr.yaml
> +# core_component: Used in the Components health feature. When true, the unhealthy scenarios will be raised as errors. Otherwise, they will be raised as a warning.
I think I prefer with the `is_` prefix to make it clear that a boolean is expected without having to refer to doc

2020-11-13 13:01 UTC, xeviknal commented
@jotak @hhovsepy approached this one too. thx

2020-11-13 14:22 UTC, jotak approved these changes
LGTM

2020-11-17 07:52 UTC, merged