[Proxy-config] Add PortForward permissions at pod level
kiali/kiali-operator pull request #213
Opened 2020-12-02 11:54 UTC by xeviknal

Kiali needs to port-forward against a pod in the mesh in order to get the envoy dump of an specific envoy.
This PR adds the necessary for the operator to add the `post|create` permissions for the `pod/portforward` subresource.

Relates to https://github.com/kiali/kiali/pull/3400
Relates to https://github.com/kiali/kiali-ui/pull/2006

2020-12-02 15:04 UTC, jmazzitelli requested changes
Just some formatting issues. To see why this is important, do a diff on the different manifests files - and then try to figure out if anything is wrong.
e.g.

```
diff manifests/kiali-{community,upstream}/1.28.0/kiali.v1.28.0.clusterserviceversion.yaml
```
On my box, this is easy to see they are essentially the same.

Now do this:

```
diff manifests/kiali-community/1.28.0/kiali.v1.28.0.clusterserviceversion.yaml manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
```
Right now, I'm going cross-eyed seeing all these diffs and I have no idea what happened. This isn't anything you did in this PR, but I'm illustrating what kind of problems we are going to have if we do not maintain  consistency throughout all of these manifest files. I'll have to figure out what, if anything, is really different between kiali-ossm and kiali-community and fix anything missing.

2020-12-02 15:08 UTC, jmazzitelli commented
@xeviknal I don't know if I got all the places, but hopefully you get the idea in my last review. Just make sure you put these new sections in the same, correct place in all the files, and alphabetize the list of verbs (that verb-sort issue appears to have screwed up and why I think the diffs between kiali-ossm and kiali-community exist - but I have to manually check all those diffs to make sure - this must have happened a while ago but I didn't catch it. But this is why I am so picky about getting the formatting consistent across these files, because other wise we will never figure out if we missed something or forgot something in one of these files).

2020-12-02 15:20 UTC, jmazzitelli approved these changes
looks good now

2020-12-02 15:30 UTC, xeviknal commented
@jmazzitelli it perfectly makes sense now. I might forget about this in the future but I am all in for this to reduce errors in future releases, sure. Plus, I'd never want to harm you, haha. Thanks for the thorough clarification :+1:

2020-12-03 12:09 UTC, xeviknal commented
@lucasponce @jmazzitelli I've add it one commit to add a config. It gives the option to the users to change the port which kiali will open to fetch the envoy config dump information. (changes in the helm-charts coming..)

2020-12-03 14:52 UTC, jmazzitelli approved these changes

2020-12-07 08:12 UTC, merged