[WIP] Server-side UI Defaults
kiali/kiali-operator pull request #241
Opened 2021-01-26 16:57 UTC by cfcosta

Part of https://github.com/kiali/kiali/issues/3371.

Please see: https://github.com/kiali/kiali-ui/pull/2064

2021-01-26 17:05 UTC, jmazzitelli requested changes

2021-01-26 17:05 UTC, jmazzitelli commented on roles/default/kiali-deploy/defaults/main.yml
> +      auto_refresh_interval: "15s"
Only request I have is to make sure the peer settings are alphabetically ordered:
```suggestion
    ui_defaults:
      auto_refresh_interval: "15s"
      metrics_per_refresh: "1m"
      namespaces: []
```

2021-01-26 17:05 UTC, jmazzitelli commented on deploy/kiali/kiali_cr.yaml
> +#        auto_refresh_interval: "15s"
Only request I have is to make sure the peer settings are alphabetically ordered:
```suggestion
# How long should the interval be between each graph refresh. Omit for default,
# "pause" to disable auto refresh.
# Valid values: pause, 10s, 15s, 30s, 1m, 5m, 15m
#        ---
#        auto_refresh_interval: "15s"
#
# Number of metrics to get on each update. Omit for default.
# Valid values: 1m, 5m, 10m, 30m, 1h, 3h, 6h, 12h, 1d, 7d, 30d
#        ---
#        metrics_per_refresh: "1m"
#
# Defines the default namespaces selected when the graph page opens, set it to
# empty array (or omit key) for no default.
#        ---
#        namespaces: []
```

2021-01-26 17:22 UTC, jmazzitelli submitted a review, later dismissed
LGTM

2021-01-27 20:21 UTC, jshaughn requested changes
Good intial settings.  A few minor changes needed.

2021-01-27 20:21 UTC, jshaughn commented on deploy/kiali/kiali_cr.yaml
> +#        auto_refresh_interval: "15s"
This setting applies to more than just the graph.  It applies, I think, to every page offering auto refresh.  Maybe just change to:

` The automatic refresh interval for pages offering automatic refresh.`

Also, I think "automatic" is implied, so you could opt to remove "auto_".

2021-01-27 20:21 UTC, jshaughn commented on deploy/kiali/kiali_cr.yaml
> +#        metrics_per_refresh: "1m"
I'd change 'Number of...' to `Duration of..` or `Time period of...`  `..metrics to fetch on each refresh`.

2021-01-27 20:21 UTC, jshaughn commented on deploy/kiali/kiali_cr.yaml
> +#        namespaces: []
Again, this has greater scope than the graph.  Something like:

`Default selections for the Namespace Selection dropdown.  Non-existent of inaccessible namespaces will be ignored. 
 Omit, or set to an empty array, for no default namespaces.`

2021-02-08 15:08 UTC, cfcosta commented
@jshaughn added your feedback, will rename the keys to remove the `auto_` from the name, as it is indeed implied.

2021-02-08 15:31 UTC, jmazzitelli requested changes

2021-02-08 15:31 UTC, jmazzitelli commented on deploy/kiali/kiali_cr.yaml
> +#
Remove odd characters. No need for blank line before the "---" line.
```suggestion
# Default settings for the UI. These defaults apply to all users.
```

2021-02-08 15:31 UTC, jmazzitelli commented on roles/default/kiali-deploy/defaults/main.yml
> +      icon_annotation: "kiali.io/api-type"
Revert this file - the indentation is screwed up.

2021-02-09 14:55 UTC, jmazzitelli requested changes
opps... sort the settings

2021-02-09 14:55 UTC, jmazzitelli commented on deploy/kiali/kiali_cr.yaml
> +#      metrics_per_refresh: "1m"
```suggestion
# Duration of metrics to fetch on each refresh. Omit for default.
# Valid values: 1m, 5m, 10m, 30m, 1h, 3h, 6h, 12h, 1d, 7d, 30d
#      ---
#      metrics_per_refresh: "1m"
#241 # Default selections for the namespace selection dropdown. Non-existent or
# inaccessible namespaces will be ignored. Omit, or set to an empty array for no
# default namespaces.
#      ---
#      namespaces: []
```

2021-02-09 14:55 UTC, jmazzitelli commented on roles/default/kiali-deploy/defaults/main.yml
> +      metrics_per_refresh: "1m"
```suggestion
      metrics_per_refresh: "1m"
      namespaces: []
```

2021-02-09 14:58 UTC, jmazzitelli approved these changes

2021-02-09 22:43 UTC, jmazzitelli approved these changes
I ran tests - this works.

2021-02-09 22:45 UTC, jshaughn approved these changes
LG

2021-02-10 15:39 UTC, pbajjuri20 approved these changes

2021-02-10 15:47 UTC, merged