Introduce Graph Find/Hide presets
kiali/kiali-operator pull request #315
Opened 2021-05-17 19:04 UTC by jshaughn

Graph Find/Hide now offers preset expressions via new dropdowns on each input. The preset expressions are supplied via the UIDefaults supplied by the server, and so can be configured by users via the CR.

Part-Of https://github.com/kiali/kiali/issues/3708

Server PR: https://github.com/kiali/kiali/pull/4020
UI PR: https://github.com/kiali/kiali-ui/pull/2159

2021-05-21 10:43 UTC, lucasponce commented
I cound't test the operator, I had some local problem to build the operator. But I suspect those are completely unrelated to the PR.

2021-05-21 10:43 UTC, lucasponce approved these changes

2021-05-21 12:11 UTC, jmazzitelli requested changes

2021-05-21 12:11 UTC, jmazzitelli commented on deploy/kiali/kiali_cr.yaml
> +#            expression:  "name = unknown"
Follow the conventions everywhere else in the operator - we do not indent lists twice. So this should be:
```suggestion
#        find_options:
#        - description: "Find: slow edges (> 1s)"
#          expression: "rt > 1000"
#        - description: "Find: unhealthy nodes"
#          expression:  "! healthy"
#        - description: "Find: unknown nodes"
#          Expression:  "name = unknown"
#        hide_options:
#        - description: "Hide: healthy nodes"
#          expression: "healthy"
#        - description: "Hide: unknown nodes"
#          expression:  "name = unknown"
```

2021-05-21 12:11 UTC, jmazzitelli commented on roles/default/kiali-deploy/defaults/main.yml
> +            expression:  "name = unknown"
Follow the conventions everywhere else in the operator - we do not indent lists twice. So this should be:
```suggestion
        find_options:
        - description: "Find: slow edges (> 1s)"
          expression: "rt > 1000"
        - description: "Find: unhealthy nodes"
          expression:  "! healthy"
        - description: "Find: unknown nodes"
          Expression:  "name = unknown"
        hide_options:
        - description: "Hide: healthy nodes"
          expression: "healthy"
        - description: "Hide: unknown nodes"
          expression:  "name = unknown"
```

2021-05-24 17:55 UTC, jmazzitelli approved these changes

2021-05-24 21:05 UTC, mattmahoneyrh approved these changes

2021-05-24 21:11 UTC, merged