Add configuration for custom metric aggregations
kiali/kiali-operator pull request #428
Opened 2021-09-24 15:48 UTC by israel-hdez

Related kiali/kiali#2911

Back-end PR: kiali/kiali#4390

2021-09-28 17:37 UTC, pbajjuri20 submitted a review, later dismissed
I have verified the backend PR, with this operator PR.

2021-09-28 18:03 UTC, jmazzitelli requested changes

2021-09-28 18:03 UTC, jmazzitelli commented on deploy/kiali/kiali_cr.yaml
> +# The following is an example about how to configure additional aggregations (not default values).
I would make it clear what the actual default values are:

```suggestion
# The following is an example about how to configure additional aggregations.
# These are not the default values; the actual default value for both metrics_inbound and metrics_outbound aggregations is an empty list.
```

2021-09-29 17:35 UTC, israel-hdez commented
Praneeth has already approved. So, I'll merge.

2021-09-29 17:37 UTC, merged