Add 1.46 role
kiali/kiali-operator pull request #484
Opened 2022-02-01 14:19 UTC by aljesusg

1.46 will be replaced by 1.48 

Do not merge

2022-02-02 18:05 UTC, jmazzitelli requested changes
Aside from the help text that needs to change in the CSV, this looks good.

But can you confirm that the `roles/v1.46` is simply a copy of the current `roles/default`? That's what it should be (I just want to make sure you didn't copy `roles/v1.36` - the new version should be a copy of the `roles/default` directory).

I also +1 the changes you made to add the new 1.46 to the default supported images. That is all correct.

2022-02-02 18:05 UTC, jmazzitelli commented on manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
> +    [kiali_cr.yaml](https://github.com/kiali/kiali-operator/blob/v1.46/deploy/kiali/kiali_cr.yaml)
This section (lines 104-106) is different now. 1.46 branch won't have the kiali_cr yaml - so you need to change this to look like what master looks like now: https://github.com/kiali/kiali-operator/blob/master/manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml#L104-L106

```
    For quick descriptions of all the settings you can configure in the Kiali
    Custom Resource (CR), see
    [the kiali.io docs](https://kiali.io/docs/configuration/kialis.kiali.io/).
```

2022-02-02 18:54 UTC, aljesusg commented
> Aside from the help text that needs to change in the CSV, this looks good.
> 
> 
> 
> But can you confirm that the `roles/v1.46` is simply a copy of the current `roles/default`? That's what it should be (I just want to make sure you didn't copy `roles/v1.36` - the new version should be a copy of the `roles/default` directory).
> 
> 
> 
> I also +1 the changes you made to add the new 1.46 to the default supported images. That is all correct.

I am 100% sure that I copied the 1.36 and not the default 🤣 let me change it 😊

2022-02-06 22:09 UTC, jmazzitelli approved these changes

2022-02-07 06:47 UTC, aljesusg commented
I think @jmazzitelli that if we are going to update this later to the version 1.48 we can avoid this merge and only do the PR to the branch 1.46 https://github.com/kiali/kiali-operator/pull/488 . What do you think?

2022-02-07 10:10 UTC, jmazzitelli commented
> only do the PR to the branch 1.46 #488 . What do you think?

yes, that's a good idea.

2022-02-07 10:25 UTC, aljesusg commented
Closed in favor https://github.com/kiali/kiali-operator/pull/488

2022-02-07 10:25 UTC, closed without merging