New Tempo grafana datasource settings
kiali/kiali-operator pull request #749
Opened 2024-03-14 14:06 UTC by josunect

For the new Grafana URL format, Kiali will need to know the Grafana Tempo Datasource UID and the org Id in order to generate the trace/span links.

Ref. https://github.com/kiali/kiali/pull/7085

2024-03-15 16:04 UTC, jmazzitelli requested changes
alphabetize ;)

2024-03-15 16:04 UTC, jmazzitelli commented on crd-docs/cr/kiali.io_v1alpha1_kiali.yaml
> +        datasource_uid: ""
```suggestion
        datasource_uid: ""
        org_id: ""
```

2024-03-15 16:04 UTC, jmazzitelli commented on crd-docs/crd/kiali.io_kialis.yaml
> +                            type: string
```suggestion
                          datasource_uid:
                            description: "The unique identifier (uid) of the Tempo datasource in Grafana."
                            type: string
                          org_id:
                            description: "The Id of the organization that the dashboard is in. Default to 1 (the first and default organization)."
                            type: string
```

2024-03-15 16:04 UTC, jmazzitelli commented on roles/default/kiali-deploy/defaults/main.yml
> +        datasource_uid: ""
```suggestion
        datasource_uid: ""
        org_id: ""
```

2024-03-15 16:13 UTC, josunect commented
> alphabetize ;)

Right!

2024-03-15 16:36 UTC, jmazzitelli approved these changes

2024-03-19 15:17 UTC, merged

2024-03-22 10:57 UTC, josunect commented
Doc PR: https://github.com/kiali/kiali.io/pull/764