Remove kiali 1.57 out support
kiali/kiali-operator pull request #844
Opened 2024-11-11 20:57 UTC by aljesusg

Remove kiali 1.57 out support

# Supporting

## Kiali
- Kiali 1.65
- Kiali 1.73
- Kiali 2.X

## OSSMC

- OSSMC 1.73
- OSSMC 2.X

2024-11-11 22:30 UTC, jshaughn commented
Assuming TP2 uses Kiali 2.1, this should be OK to apply to master now that 2.1 is out.

2024-12-02 15:55 UTC, jmazzitelli approved these changes

2024-12-10 14:42 UTC, jshaughn submitted a review, later dismissed
LGTM!

2024-12-10 14:46 UTC, jmazzitelli requested changes
https://github.com/kiali/kiali-operator/blob/master/playbooks/ossmconsole-default-supported-images.yml

remove 2.1 from here also

2024-12-10 15:11 UTC, jmazzitelli approved these changes

2024-12-10 15:20 UTC, merged