Add new graph setting for the animation style
kiali/kiali-operator pull request #851
Opened 2024-11-22 23:24 UTC by jshaughn

Part-of https://github.com/kiali/kiali/issues/7934

2024-11-23 01:12 UTC, jmazzitelli commented on crd-docs/crd/kiali.io_kialis.yaml
> +                                enum: ["dash", "point" ]
Egad! No leading space in the front, but leading space at the end? UG-LY.

```suggestion
                                enum: ["dash", "point"]
```

2024-11-25 02:09 UTC, jmazzitelli requested changes
You forgot to add the default to the example CR, and I just noticed we are missing all of the settings here. So you should add them. This example CR file is used for 2 things  (a) for an example CR that users can refer to, each value in the example CR file is the default, so users can use this as a reference for all default values, and
(b) this file is used to test the schema validation - our CI action runs a validation test on the example CR which confirms the schema and example files are both valid.

So in this file: https://github.com/kiali/kiali-operator/blob/v2.1.0/crd-docs/cr/kiali.io_v1alpha1_kiali.yaml#L437

you need to add this:
```yaml
        settings:
          animation: "point"
          font_label: 13
          min_font_badge: 7
          min_font_label: 10
```

2024-11-25 14:10 UTC, jshaughn commented
> You forgot to add the default to the example CR, and I just noticed we are missing all of the settings here

I will add the new one, but the others are actually purposefully unadvertised, and also will go away with the cytoscape deprecation.

2024-11-25 16:14 UTC, jmazzitelli approved these changes
validation passes. lgtm

2024-12-05 20:31 UTC, merged